apiVersion: v1
kind: BuildConfig
metadata:
  name: pipeline-inspector
  app: welcome 
  labels:
    name: pipeline-inspector
spec:
  runPolicy: Serial
  source:
    type: "Git"
    git:
      uri: "https://github.com/wilsonchoi1/openscap-openshift.git"
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: pipeline/Jenkinsfile 
  output:
  resources:
  postCommit:
